<!-- Data table plugin--> 
<script src="{{ asset('js/plugins/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('DataTables/DataTables-1.10.20/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('DataTables/DataTables-1.10.20/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('DataTables/Buttons-1.6.1/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('DataTables/Buttons-1.6.1/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('DataTables/JSZip-2.5.0/jszip.min.js') }}"></script>
<script src="{{ asset('DataTables/pdfmake-0.1.36/pdfmake.min.js') }}"></script>
<script src="{{ asset('DataTables/pdfmake-0.1.36/vfs_fonts.js') }}"></script>
<script src="{{ asset('DataTables/Buttons-1.6.1/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('DataTables/Buttons-1.6.1/js/buttons.print.min.js') }}"></script>
